
= Introduction
This project aims to research and develop a language learning website for the endangered language Scottish Gaelic (Gaidhlig). Two essential aspects will be discussed: how languages are best learned, and how those techniques apply to a digital application such as a website.

The Gaidhlig language is endangered, and while there are accessible ways to learn it, they don't work for everyone and don't cater for all learning styles. Tools like SpeakGaelic exist, which provide structured television and podcast episodes alongside a website with quizzes on their content. Duolingo has a course for Gaidhlig\; however, it doesn't teach common phrases or words, and doesn't stick to a singular dialect during beginner teaching. These tools do work for a large group of people, but some rely on more interactive and specialised learning techniques. Such tools are rare, and most people don't have Gaidhlig speakers in their lives to help them.

The project aims to create a conversation-based learning resource. It will have set human-written units structured as a single conversation. The units will start simple, use common words, and focus on a specific topic per unit. Each unit will administer a variety of techniques and quizzes that help the language stick in a user's mind. It will provide appropriate feedback that doesn't overwhelm the user while remaining constructive. These requirements will be supported by a literature review that delves into these topics and related ones to help evolve the project idea.

!temporary! non written out aims:
- Analyse literature on language learning techniques (e.g. quizzing types, media formats, feedback, design, product experience & communication), motivation blockers, and relevant LLM topics to language
- Create a language learning site for Scottish Gaidhlig with a sufficient design process
- Each unit is a pre-written conversation, displayed to the user (where this app shines, no other app that offers Gaidhlig as a resource does this in an interactive digital-first form)
- The user will be asked questions in quizzes based on the conversation along side other activities to be researched
- It will utilise quizzing techniques analysed in the literature review
  - Including but not limited to: spaced repetition, constructive feedback, mistake tracking
- May be supplemented by the same as above, but instead of units, it is represented as 'homework' or 'practice' and the conversations are dynamically generated by an LLM (which is given the statistics of what the user needs to improve on)
- Evaluate the project in ways outlined below

== Project Schedule Aim

As was outlined in the initial project overview, here is a set of milestones I expect to achieve during the project:
1. Literature review draft & interim check-up - November 14, 2025.
2. Literature review completion - 19th December 2025.
3. Application design completion - January 23, 2026
4. Application implemented & tested - February 20, 2026
5. Dissertation & evaluation completion - April 15, 2026
6. Submission & presentation - April 22, 2026

== Evaluation Plan

To evaluate the project, I aim to create scores in terms of user experience (UX), effectiveness, and critical comparison with prior art.

UX is defined here as the ease of use and navigation of the site. To figure this out, I will present the site to a small group of users and ask them to complete a set of tasks. The friction they experience will be documented and analysed.

Effectiveness is defined as how easily someone can pick up a portion of the language using the site. This would be analysed one week after initially presenting the site to a user, and asking them, verbally or in text, to explain what a word or phrase means. As this is a proof-of-concept site, it will not have enough units for a user to become conversational, but they should be able to gain some common words.

Finally, I will critically compare the site with prior art. This will include a comparison of the features offered alongside how they align with the literature in the literature review. I will also analyse the previous two metrics to determine whether the issues people note with this solution are present in the prior art.
#pagebreak(weak: true)
