= Conclusion

This project set out to investigate how Mobile-Assisted Language Learning (MALL) and Computer-Assisted Language Learning (CALL) frameworks could be applied to learning Gaidhlig through a pre-scripted conversation-based online application. The project aimed to create an accessible and engaging learning experience for people wanting to learn the language, supported by combinations of pedagogical approaches such as spaced repetition retrieval practice and context-aware learning.

The evaluation results suggest that the system was effective in introducing and reinforcing basic language concepts. Users were generally able to recall the material presented within conversations, with all participants who completed the quiz answering later questions correctly. This indicates that the conversational format and repetition mechanisms support recall. As well as this, the system aligned well with several aspects of the PF4M framework, particularly in terms of learner control, accessibility, and usability. However, some inconsistencies in performance suggest that retention was not uniform across all content.

In relation to the original aims, the project can be considered partially successful. The system demonstrates that a conversation-based approach can support engagement and initial learning, and that mobile delivery is suitable for short, flexible learning sessions. However, limitations in participation and depth of evaluation mean that the findings cannot be generalised beyond this small sample. Furthermore, while the system incorporates pedagogical concepts, it does not yet fully realise adaptive or personalised learning, which limits its effectiveness for a wider range of learners.

Several limitations impacted the outcome of the project. The largest was a small sample size and a low response rate, which restricts the reliability of the evaluation. Additionally, the optional nature of parts of the survey reduced participation in the final section, which arguably is important for a reliable evaluation. 

From a design perspective, the system follows a majorly linear structure, which limits its ability to adapt to individual learner needs. Other factors identified in the literature, such as pronunciation support and social interaction, were not implemented, further narrowing the scope of the evaluation.

The survey findings also highlight limitations in recognition and recall; it is less effective in developing deeper language understanding and learner confidence, particularly because it doesn't support speaking and real-time interaction. Additionally, the system currently relies on manually written content rather than dynamic composition of content, which limits scalability.

Despite these limitations, the project demonstrates potential in combining conversational learning with mobile learning. It provides a practical demonstration of how pedagogical frameworks such as PF4M and techniques like spaced repetition can be applied in a real system, even at a small scale. The findings suggest that such approaches are promising, especially for introducing new language concepts in an easy and accessible way.

Future work could build on this foundation by increasing the scale of evaluation and improving system adaptability. This may include implementing personalised learning features, integrating pronunciation systems, and expanding the range and types of content. Additionally, making survey assessment components mandatory and improving communication of user expectations could increase participation and produce more reliable results. Further exploration of how conversational systems can support long-term retention and learner confidence would strengthen the contribution of this approach to mobile-assisted language learning.