= Appendix 1: Personal Appraisal

This project contains several strengths and weaknesses in relation to both my performance and the methods I employed.

A key strength of the project was the structured development process used during implementation. I followed established DevOps practices, including a branching strategy, pull requests, issue tracking, automated AI-assisted review, and unit testing. These practices helped me maintain a consistent and organised workflow, reducing the likelihood of regressions and allowing features to be developed incrementally. This was particularly valuable in a solo project context, where maintaining oversight of everything going on is critical.

Another strength was the use of existing technologies such as NextJS, ShadCN, and Convex. This allowed the development effort to be focused on the core aspects of the project, specifically UI design and the implementation of business logic, rather than having to maintain infrastructure or complex deployments. This decision reduced complexity and enabled faster iteration, although it also meant that certain architectural decisions were at risk of being constrained by the capabilities of these tools.

However, there were also notable weaknesses in my approach. During implementation, I frequently overengineered aspects of the system, particularly the unit storage format. This resulted in unnecessary complexity and became a time sink when implementing surrounding logic and UI. This issue largely came from attempting to design a flexible system before fully understanding the requirements. This highlights a need to prioritise simplicity and iterative refinement in future projects.

The literature review also lacked focus in some areas due to an initially broad scope. While it covered a wide range of relevant topics, not all of these were aligned with the final implementation. The reason for this is that during the planning and research phase, I was interested in incorporating a larger set of features into the site, but lacked sufficient time to fully include them. A more focused review, directly aligned with the system’s design decisions, would have strengthened the pedagogical grounding of the application.

Time management was another challenge throughout the project. Periods of burnout and fluctuating pacing resulted in missing planned deadlines, which created additional pressure towards the later stages of development. Despite this, the project was completed on time, demonstrating an ability to recover and reprioritise work when necessary. However, this experience highlights the importance of maintaining consistent progress and potentially breaking down tasks into smaller goals. 

In terms of personal development, this project significantly improved my ability to design and implement a full-stack application from research through to evaluation. I developed a stronger understanding of how to translate pedagogical theory, such as MALL and spaced repetition, into practical system design decisions. I also gained experience in structuring learning content and designing accessible interfaces. These skills represent a meaningful progression in both my technical and research capabilities.