import { ConvexAuthNextjsServerProvider } from "@convex-dev/auth/nextjs/server";
import type { Metadata } from "next";
import { ThemeProvider as NextThemesProvider } from "next-themes";
import { Geist, Geist_Mono } from "next/font/google";
import { PropsWithChildren } from "react";

import { TooltipProvider } from "@/components/ui/tooltip";
import { cn } from "@/lib/utils";
import { ConvexClientProvider } from "@/providers/ConvexClientProvider";

import "./globals.css";

const geistSans = Geist({
    variable: "--font-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-mono",
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({ children }: PropsWithChildren) {
    return (
        <ConvexAuthNextjsServerProvider>
            <html lang="en" suppressHydrationWarning>
                <body
                    className={cn(
                        "antialiased",
                        geistSans.variable,
                        geistMono.variable,
                    )}
                >
                    <ConvexClientProvider>
                        <TooltipProvider>
                            <NextThemesProvider
                                attribute="class"
                                defaultTheme="system"
                                enableSystem={true}
                                disableTransitionOnChange
                            >
                                {children}
                            </NextThemesProvider>
                        </TooltipProvider>
                    </ConvexClientProvider>
                </body>
            </html>
        </ConvexAuthNextjsServerProvider>
    );
}
